### ISSUE TITLE
Multiversion support

### ISSUE THREAD

**Issue by sowelipililimute** [ZockerAxel/CrazyAdvancementsAPI#12]
It seems that each version of CrazyAdvancementsAPI only supports one version. Would it be possible to get multiversion support?

**Comment by ZockerAxel** [comment]
There are multiple reasons why multiversion support will not be added:

1. I work solo on this project in my free time and I don't have the time to support multiple versions
2. I do not want to increase the File Size just to support multiple versions. This API is supposed to be leightweight, both in how it works and in it's size
3. Most of the time older versions still have a working API version that works without major issues (of course there are still some not so nice bugs and they lack new features)
