### ISSUE TITLE
Duplicate toast & other questions

### ISSUE THREAD

**Issue by MinePenguin** [ZockerAxel/CrazyAdvancementsAPI#3]
I am creating my advancements like so in my onEnable method:

```java
for(Stamp stamp : Stamp.values()) {
			AdvancementDisplay rootDisplay = new AdvancementDisplay(Material.ARMOR_STAND, "Stamp Earned!", stamp.getName(), AdvancementFrame.TASK, true, false, AdvancementVisibility.HIDDEN);
			rootDisplay.setBackgroundTexture("textures/block/concrete_yellow.png");
			Advancement root = new Advancement(null, new NameKey("minepenguin", "STAMP_" + stamp.name()), rootDisplay);
			advancementManager.addAdvancement(root);
}
```

And then I am trying to send a toast to the player like so:
```java
MinePenguin.advancementManager.addPlayer(p);
MinePenguin.advancementManager.grantAdvancement(p, MinePenguin.advancementManager.getAdvancement(new NameKey("minepenguin", "STAMP_" + stamp.name())));
MinePenguin.advancementManager.removePlayer(p);
```

However, I seem to be getting two toasts for a reason that's beyond me:
![](https://i.thomas.best/2d2a697a-bee7-4e16-a7f7-1ed3beaca3eb.png)

Am I doing something wrong?

And, is there any way to change the text of 'Advancement Made!'? Is this something that could be done through the api or by a texture pack?

Thank you & stay safe.

**Comment by ZockerAxel** [comment]
Hey MinePenguin,
the Double Toast is a known issue but i don't have the time to fix it, so the recommended workaround is to set the showToast boolean to false and display a Toast using the Advancement#displayToast(Player player) method when you grant the advancement.

The "Advancement Made!" is one of three different translations that can be changed via a resource pack (you can switch between the three translations by changing the AdvancementFrame of the display).

If you have any further questions, don't hestitate to ask.

**Comment by MinePenguin** [comment]
Thank you :)

**Comment by ZockerAxel** [comment]
Hey again,
i just saw that you only want to send a toast notification, for that you don't need to add the advancements to a manager, you can just straight up use the method to show toasts
