### ISSUE TITLE
Can you add this to a maven repository?

### ISSUE THREAD

**Issue by unlimitedcoder2** [ZockerAxel/CrazyAdvancementsAPI#4]
Could you add this to a maven repo?

**Comment by ZockerAxel** [comment]
Unfortunately, i don't have a lot of time to look into adding the API to a maven repository but on the project discord some nice people have discovered a workaround to use it as a maven dependency.

**Comment by jely2002** [comment]
I have made a fork that is a maven repository and can be included in your project. Check it out here [StandaloneCrazyAdvancementsAPI](https://github.com/jely2002/StandaloneCrazyAdvancementsAPI)
I will be updating my fork to 1.16.4 later this night.
