### ISSUE TITLE
If addPlayer() fails or doesn't happen, saved progress resets

### ISSUE THREAD

**Issue by Azami7** [ZockerAxel/CrazyAdvancementsAPI#8]
If addPlayer() does not happen for whatever reason, the player's progress towards advancements is overwritten by any save that happens (in my case, saving on logout).

Save file before login:
{"pottercraft:read_letter":["criterion.0"]}

Save file after quit:
{"pottercraft:read_letter":[]}

I am not sure if this is intended behavior or not but it doesn't seem like a good thing since a bug in someone's plugin could result in clobbering advancement progress.

**Comment by ZockerAxel** [comment]
It is not intended to save progress for players that are not in the advancement manager. However there is another bug that requires me to change the save and load methods which should fix this issue too.

**Comment by Azami7** [comment]
Thanks - happy to help test this once you have a fix.

**Comment by ZockerAxel** [comment]
it should be fixed in the latest version

**Comment by Azami7** [comment]
Downloaded! I'll let you know if I see any concerns but so far it looks good.
